sudo: required
services:
    - docker

before_install:
    - docker build -t amitrii/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true amitrii/react-test npm test -- --coverage

after_sucess:
    - docker build -t amitrii/multi-client ./client
    - docker build -t amitrii/multi-nginx ./nginx
    - docker build -t amitrii/multi-server ./server
    - docker build -t amitrii/multi-worker ./worker

    - echo  "DOCKER_PASSWORD" | docker  login  -u  "DOCKER_ID" --password-stdin
    - docker push amitrii/multi-client:latest
    - docker push amitrii/multi-nginx:latest
    - docker push amitrii/multi-server:latest
    - docker push amitrii/multi-worker:latest

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: "elasticbeanstalk-us-east-2-481611874253"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    